
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const montserrat = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "300"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.className} ${montserrat.className} antialiased`}>
      <body>
        {children}
      </body>
    </html>
  );
}
